[theme]
base            = "dark"
primaryColor    = "#74c7ec"
backgroundColor = "#1e1e2e"
secondaryBackgroundColor = "#313244"
textColor       = "#cdd6f4"
font            = "sans serif"

[server]
headless        = true
port            = 8501
enableXsrfProtection = false

[browser]
gatherUsageStats = false
